version: '3.1'

services:
  tecnoride-db:
    container_name: postgresql-tecnoride
    image: postgres:15.1
    environment:
      POSTGRES_DB: tecnoride-db
      POSTGRES_USER: tecnoride-postgres-user
      POSTGRES_PASSWORD: tecnoride-postgres-pwd
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge